# Generated by Django 5.0.6 on 2024-05-29 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobs_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='description',
        ),
    ]
